### ISSUE TITLE
Value on instances

### ISSUE THREAD

**Issue by MiniMinerLPs** [flyth/ts3soundbot#206] opened 2015-04-23 10:05 UTC
Hello,

how can i change the value of instances?

**Comment by nrauschcom** [comment] 2015-04-23 10:06
What's the "value" of an instance..?

**Comment by MiniMinerLPs** [comment] 2015-04-23 10:09
Sorry my english isn't very well... i can only add 5 instances... how can I add more?

**Comment by nrauschcom** [comment] 2015-04-23 10:14
That's not possible at the moment.

Also, this is a duplicate of #198.
Read there for more information.

**Comment by flyth** [comment] 2015-04-23 10:27
Note to self: create a FAQ page **really** soon.

**Closed by flyth** 2015-04-23 10:27 UTC

**Comment by MiniMinerLPs** [comment] 2015-04-23 10:32
xD I installed a second music bot ^^

**Comment by MiniMinerLPs** [comment] 2015-04-23 10:33
on Port :8088 :)
