### ISSUE TITLE
[Request] Volume Offset

### ISSUE THREAD

**Issue by Krachbummente1337** [flyth/ts3soundbot#247] opened 2015-05-12 21:28 UTC
Hey,

I have another suggestion for the soundbot:
an offset value that you can adjust at the tag-editor to increase or decrease the volume of a non-normalized sound file.

Regards,
KBE.

**Comment by flyth** [comment] 2015-05-12 23:21
Duplicate of #8

**Closed by flyth** 2015-05-12 23:21 UTC
Labels: duplicate
