### ISSUE TITLE
[Feature Request] !Queue

### ISSUE THREAD

**Issue by UnwishingMoon** [flyth/ts3soundbot#123] opened 2015-03-16 19:04 UTC
Hello,

Can you add a feature called Queue where the music goes in Queue???
And (if possible) can you add a permissions group?? because I would set this permissions without other people can stop the current music, can you add a comand or feature??

**Comment by flyth** [comment] 2015-03-16 19:05
Duplicate of #28

**Closed by flyth** 2015-03-16 19:05 UTC
Labels: duplicate
