### ISSUE TITLE
Ducking always resets to 50%

### ISSUE THREAD

**Issue by shawly** [flyth/ts3soundbot#124] opened 2015-03-17 13:51 UTC
Like the title says, the ducking value always resets to 50% after logging out and back in.
I haven't tested yet if the value is only a visual bug or really gets reset though.

LogLevel was set to 10 but nothing was logged in the last 24 hours, so it could be a frontend bug.

`2015-03-16T17:15:14+01:00 PLAYLIST-ENTRY-ADD [admin] 1ae89e5f-a958-4f79-a854-cbbc0194d8e3 2be5908e-9428-4b3a-ad15-60337940a738 OK`
`2015-03-16T17:16:05+01:00 PLAYLIST-CREATE [admin] Rap OK`
`2015-03-17T14:41:14+01:00 LOGIN [admin] FAIL`
`2015-03-17T14:41:18+01:00 LOGIN [admin] OK`

**Comment by flyth** [comment] 2015-03-17 14:16
That log is from the "Bot Log"? Because settings are handled by an instance, so it would appear in the "Instance Log". If it doesn't log anything, it doesn't save the settings at all - which would be a much bigger bug.

**Comment by shawly** [comment] 2015-03-17 14:23
I'm sorry the Instance Log say `2015-03-17T14:42:08+01:00 Storing configuration.`
When I change the ducking value, but it didn't say anything that it saved it to 50% so it may be a frontend bug.

Also I just tried to relog and I was wrong it does stay at the specified value even when relogging, but it resets to 50 if I restart the whole tsbot (not the instance).

**Comment by flyth** [comment] 2015-03-17 14:25
Ah, I can confirm _that_. Will be fixed in the next version.

**Comment by flyth** [comment] 2015-03-19 17:12
Fixed.

**Closed by flyth** 2015-03-19 17:12 UTC
