### ISSUE TITLE
[Feature Request] Radiolist

### ISSUE THREAD

**Issue by MrJoki007** [flyth/ts3soundbot#67] opened 2015-02-28 22:04 UTC
A playlist for Radio stations that you have your favourite radio stations in a list and then a command !radio <name> (nickname you gave the radio in the list)

**Comment by flyth** [comment] 2015-02-28 22:10
Duplicate of #34

**Comment by MrJoki007** [comment] 2015-02-28 22:10
Sry didnt see that

**Closed by flyth** 2015-02-28 22:10 UTC
