### ISSUE TITLE
Suggestion: Groups for controlling the bot

### ISSUE THREAD

**Issue by Trantium** [flyth/ts3soundbot#128] opened 2015-03-17 22:38 UTC
Hello, 

Is it possible to allow certain servergroups to control the bot only by using commands?

**Comment by flyth** [comment] 2015-03-17 22:39
Duplicate of #71

**Closed by flyth** 2015-03-17 22:39 UTC
Labels: duplicate

**Comment by Trantium** [comment] 2015-03-17 22:49
Ah! Bitte, sorry my deutsch is not that good!

Also, is there a way yet to increase the max number of users meanwhile?

Anyway, thank you very much for this awesomeness. I will definitely donate!

**Comment by flyth** [comment] 2015-03-17 22:53
Ah, I'm sorry - I will translate that post :) Haven't even noticed that while reading.

There's no way right now to increase the user limit, but the next version will most likely have that limitation removed / set to 1000 (for security reasons, so that the database doesn't get blown up).

And thanks for the kind words :)

**Comment by Trantium** [comment] 2015-03-17 22:59
1 other small question, am i doing it right when changing the port and paths to run 2 bots simultaniously with a different database? I am running the bot1 on 8081 and bot2 on 8082. However, someone from 8082 can play music somehow on bot1.

Which is impossible, as they have seperate databases.

screen xinit /home/Bot1/ts3bot -- /usr/bin/Xvfb :1 -screen 0 800x600x16 -ac


screen xinit /home/Bot2/ts3bot -- /usr/bin/Xvfb :2 -screen 0 800x600x16 -ac

Am i doing it right like this?

**Comment by flyth** [comment] 2015-03-17 23:09
That way is not supported and might break due to the internal usage of ports.

The bot is able to handle multiple independent instances without starting it several times, but right now that's limited to the hoster version. There will be another release for non-profits that want to host the bot for friends for free, probably by the end of April.
So if you don't want to wait, feel free to experiment - but be aware that updates might break things without notice.
