### ISSUE TITLE
Current bugs I have

### ISSUE THREAD

**Issue by Khailz** [flyth/ts3soundbot#46] opened 2015-02-23 03:48 UTC
- Searching a song twice will create a blank page (Same goes for searching from any other place other than a playlist or all music tab)

- You can't remove the download files jobs.

- Some songs have a problem where they increase in speed for some odd reason when playing. Even if they played fine before.

- After playing for so many hours two songs will play at the same time.

Biggest bug: Uploads don't work

**Comment by JanDevDE** [comment] 2015-02-23 03:55
Hmm ... for me it works everything except point. 1 and 2

**Comment by wobberweiss** [comment] 2015-02-23 09:23
I can confirm uploads not working anymore. It looks like files are uploaded to the server but not shown on the page

**Comment by flyth** [comment] 2015-02-23 14:08
Upload should work again, sorry for that.

What do you mean by "search twice"? Once you hit enter, you will currently get a blank page because that triggers a search via external plugins (which you don't have right now). I'll try to make that a bit more user-friendly.

Are you able to reproduce the speed increase or does it happen randomly?

**Comment by Khailz** [comment] 2015-02-23 17:47
Speed increase is random but it happens with a certain song I have often. There is no log entry about it but it just seems to happen I'll see if I can get more detail out of it.

**Comment by flyth** [comment] 2015-02-23 18:38
Thanks :)

**Comment by flyth** [comment] 2015-02-24 08:46
I will close this one now, please post a new separate issue once you got more information on the speed-ups, thanks!

**Closed by flyth** 2015-02-24 08:46 UTC
