### ISSUE TITLE
Permission Suggestions and Bugs

### ISSUE THREAD

**Issue by nicb19** [flyth/ts3soundbot#204] opened 2015-04-22 20:04 UTC
It would be good to have individual permissions for each bot, so someone could be assigned permission to control a single bot instead of all of them.

Also, we've had a few issues whereby a user creates an account using the !register command and then create a password using !password. However, the password doesn't seem to work, but when I change their password in the settings, it then works.

The other issue I've encountered is that sometimes the page doesn't refresh properly (e.g. it says it's still playing the previous song). It also says it's still connected when it gets kicked from the server.

Final issue - when a bot is sticky, it won't return back to its default channel if there is a password on the channel.

Great addon for TS3 though - thanks!!

**Comment by Bielecki** [comment] 2015-04-24 13:37
He's right with permission system. I'd like it too. Also I can confirm bug with !password.

**Comment by supimfuzzy** [comment] 2015-05-26 03:49
Being able to set default permissions when someone registers or giving a user permissions based on their TS3 permissions would also be a nice addition.

**Comment by Topsii** [comment] 2015-05-29 08:34
Can also confirm the bug with !password.

Also I'm not sure, but does it make a difference if you use some uppercase letters when registering (the bot creates users in lowercase letters) and then you type the name containing uppercase letters when trying to login?

Anyways for now the only way that works for me is to set the password for each user as an admin. And even after that the users sometimes can't login though I can login into their account. Are they just doing  it wrong or is that some cache related problem (it doesn't make sense to me, but it happened with 3 different users already)

**Comment by flyth** [comment] 2015-05-29 08:48
!password has been fixed in 0.9.8 two days ago. :)

**Comment by Topsii** [comment] 2015-05-29 20:17
I've ran ts3bot -update, but I got no feedback.
How can I confirm which version I'm using?

**Comment by flyth** [comment] 2015-05-29 20:20
Sorry, it's pretty silent and shy right now... But if it didn't report an error, it did its job. :)

**Comment by BlueFreakLP** [comment] 2015-06-30 21:17
it works..

**Closed by BlueFreakLP** 2015-06-30 21:17 UTC
