### ISSUE TITLE
[Request] Blocking some Videos

### ISSUE THREAD

**Issue by UnwishingMoon** [flyth/ts3soundbot#262] opened 2015-05-23 16:04 UTC
HI,

can you add a zone where you add a link and this link will be blocked when someone try to download it (the bot doesn't download and doesn't play this videos/audiofiles), with an error message when say "this link is blocked", if possible.
Thx

-Moon

**Comment by BlueFreakLP** [comment] 2015-06-30 21:12
Duplicate of #189

**Closed by BlueFreakLP** 2015-06-30 21:12 UTC
