### ISSUE TITLE
Stream youtube

### ISSUE THREAD

**Issue by Doc94** [flyth/ts3soundbot#222] opened 2015-04-30 00:40 UTC
I knew of a good music system ts admitting links to youtube but not unloaded but it reproduced it directly ...
Which it is a payment system music (shame to be poor) what I wonder is that it is possible to do that here.

**Comment by nrauschcom** [comment] 2015-04-30 08:33
Duplicate of #216

**Comment by flyth** [comment] 2015-05-21 22:12
Next version will only temporarily store youtube-files. However, download before playback will still happen - there's no easy way around this. But on servers with fast access to the internet that shouldn't really be a problem.

**Closed by flyth** 2015-05-21 22:12 UTC
